insert into employee values(1,'suresh.kumar@gmail.com','Suresh','Kumar');
insert into employee values(2,'ramesh.yadav@gmail.com','Ramesh','Yadav');
insert into employee values(3,'keerti.verma@gmail.com','Keerti','Verma');
insert into employee values(4,'priyanka.sharma@gmail.com','Priyanka','Sharma');
insert into employee values(5,'rahul.singh@gmail.com','Rahul','Singh');
insert into employee values(6,'rahul.more@gmail.com','Rahul','More');
insert into employee values(7,'divya.joshi@gmail.com','Divya','Joshi');
insert into employee values(8,'bhuwan.agarwal@gmail.com','Bhuwan','Agarwal');
insert into roles values(1, 'ADMIN');
insert into users values (1,'$2a$12$W.7oxO8WybyPJa7TOlkdMOdTM7.TsXn9NIuPNGCMWClxXqYAseO1O','employee1');
insert into users_roles values(1,1);